apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: ferris-k8s
deploy:
  kubectl:
    manifests:
    - ./k8s/*.yaml
build:
  artifacts:
    - image: andregs/ferris-k8s
      buildpacks:
        builder: paketobuildpacks/builder:tiny
        buildpacks:
          # see https://github.com/paketo-community/rust
          - paketo-community/rustup
          - paketo-community/rust-dist
          - paketo-community/cargo
          - paketo-buildpacks/procfile
        dependencies:
          paths:
            - src
            - Cargo.lock
            - Cargo.toml
            - Procfile
